<a href="https://colab.research.google.com/github/housekjh1/study-pandas/blob/main/Chapter6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install koreanize-matplotlib
import koreanize_matplotlib

Collecting koreanize-matplotlib
  Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 45.2 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from koreanize-matplotlib) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.16.0)
Installing collected packages: koreanize-matplotlib
Successfully installed koreanize-matplotlib-0.1.1

In [4]:
inspections = pd.read_csv("chicago_food_inspections.csv")
inspections.head()

                          Name             Risk
0   MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                  JETS PIZZA   Risk 2 (Medium)
2                   ROOM 1520      Risk 3 (Low)
3    MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                CHARTWELLS       Risk 1 (High)

In [17]:
inspections["Name"].values

array([' MARRIOT MARQUIS CHICAGO   ', ' JETS PIZZA ', '   ROOM 1520 ',
       ..., ' Cafe 608 ', "  mr.daniel's ", '   TEMPO CAFE '],
      dtype=object)

In [19]:
inspections["Name"].str.strip().values # 공백 제거

array(['MARRIOT MARQUIS CHICAGO', 'JETS PIZZA', 'ROOM 1520', ...,
       'Cafe 608', "mr.daniel's", 'TEMPO CAFE'], dtype=object)

In [20]:
inspections["Name"] = inspections["Name"].str.strip()

In [22]:
inspections["Risk"] = inspections["Risk"].str.strip()

In [24]:
for column in inspections.columns:
  inspections[column] = inspections[column].str.strip() # 위와 동일함 단, object(str) 타입일 경우만

In [25]:
inspections.columns

Index(['Name', 'Risk'], dtype='object')

In [31]:
inspections["Name"].str.title()

0              Marriot Marquis Chicago
1                           Jets Pizza
2                            Room 1520
3              Marriot Marquis Chicago
4                           Chartwells
                      ...
153805                       Wolcott'S
153806    Dunkin Donuts/Baskin-Robbins
153807                        Cafe 608
153808                     Mr.Daniel'S
153809                      Tempo Cafe
Name: Name, Length: 153810, dtype: object

In [34]:
inspections["Name"].str.capitalize()

0              Marriot marquis chicago
1                           Jets pizza
2                            Room 1520
3              Marriot marquis chicago
4                           Chartwells
                      ...
153805                       Wolcott's
153806    Dunkin donuts/baskin-robbins
153807                        Cafe 608
153808                     Mr.daniel's
153809                      Tempo cafe
Name: Name, Length: 153810, dtype: object

In [32]:
inspections["Name"].str.upper()

0              MARRIOT MARQUIS CHICAGO
1                           JETS PIZZA
2                            ROOM 1520
3              MARRIOT MARQUIS CHICAGO
4                           CHARTWELLS
                      ...
153805                       WOLCOTT'S
153806    DUNKIN DONUTS/BASKIN-ROBBINS
153807                        CAFE 608
153808                     MR.DANIEL'S
153809                      TEMPO CAFE
Name: Name, Length: 153810, dtype: object

In [33]:
inspections["Name"].str.lower()

0              marriot marquis chicago
1                           jets pizza
2                            room 1520
3              marriot marquis chicago
4                           chartwells
                      ...
153805                       wolcott's
153806    dunkin donuts/baskin-robbins
153807                        cafe 608
153808                     mr.daniel's
153809                      tempo cafe
Name: Name, Length: 153810, dtype: object

In [35]:
inspections["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan],
      dtype=object)

In [39]:
inspections = inspections.dropna(subset=["Risk"])

In [40]:
inspections.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 153744 entries, 0 to 153809
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Name    153744 non-null  object
 1   Risk    153744 non-null  object
dtypes: object(2)
memory usage: 3.5+ MB

In [41]:
inspections = inspections.replace(to_replace="All", value="Risk 4 (Extreme)")

In [43]:
inspections["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)'], dtype=object)

In [45]:
inspections["Risk"].str.slice(5,6)

0         1
1         2
2         3
3         1
4         1
         ..
153805    1
153806    2
153807    1
153808    1
153809    1
Name: Risk, Length: 153744, dtype: object

In [48]:
inspections["Risk"].str.slice(8, -1)

0           High
1         Medium
2            Low
3           High
4           High
           ...
153805      High
153806    Medium
153807      High
153808      High
153809      High
Name: Risk, Length: 153744, dtype: object

In [51]:
# inspections["Risk"].str.slice(8).str.replace(")", "")
inspections["Risk"].str[8:].str.replace(")", "").head()

<ipython-input-51-4d0455ebc725>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  inspections["Risk"].str[8:].str.replace(")", "").head()

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

In [53]:
has_pizza = inspections["Name"].str.lower().str.contains("pizza") # 함수 체이닝
inspections[has_pizza]

                                    Name             Risk
1                             JETS PIZZA  Risk 2 (Medium)
19         NANCY'S HOME OF STUFFED PIZZA    Risk 1 (High)
27            NARY'S GRILL & PIZZA ,INC.    Risk 1 (High)
29                   NARYS GRILL & PIZZA    Risk 1 (High)
68                         COLUTAS PIZZA    Risk 1 (High)
...                                  ...              ...
153756       ANGELO'S STUFFED PIZZA CORP    Risk 1 (High)
153764                COCHIAROS PIZZA #2    Risk 1 (High)
153772  FERNANDO'S MEXICAN GRILL & PIZZA    Risk 1 (High)
153788            REGGIO'S PIZZA EXPRESS    Risk 1 (High)
153801        State Street Pizza Company    Risk 1 (High)

[3992 rows x 2 columns]

In [54]:
customers = pd.read_csv("customers.csv")
customers.head()

                  Name                                            Address
0        Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1    Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2      Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3  Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4       Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...

In [57]:
customers["Name"].str.split(" ").head()

0           [Frank, Manning]
1       [Elizabeth, Johnson]
2         [Donald, Stephens]
3    [Michael, Vincent, III]
4          [Jasmine, Zamora]
Name: Name, dtype: object

In [59]:
customers["Name"].str.split(" ", n=1).str.get(0).head()

0        Frank
1    Elizabeth
2       Donald
3      Michael
4      Jasmine
Name: Name, dtype: object

In [63]:
customers[["First Name", "Last Name"]] = customers["Name"].str.split(" ", n=1, expand=True)

In [64]:
customers

,Name,Address,First Name,Last Name
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [66]:
customers.drop(labels="Name",axis="columns")

,Address,First Name,Last Name
0,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...
9956,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [70]:
customers.drop("Name",axis=1) # axis=1은 컬럼, 드랍 시 축을 꼭 정해줘야함

,Address,First Name,Last Name
0,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...
9956,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson